name: Build and Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: dom, curl, libxml, mbstring, zip, fileinfo
          tools: composer:v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install PHP dependencies
        run: composer install --no-interaction --no-progress

      - name: Install NPM dependencies
        run: npm ci

      - name: Create .env file
        run: |
          echo "GITHUB_TOKEN=${{ secrets.GH_TOKEN }}" > .env

      - name: Build the site
        run: |
          vendor/bin/jigsaw build production
          
      - name: Add CNAME file
        run: echo "alama.dev" > build_production/CNAME

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build_production
          branch: main
          clean: true 